### ISSUE TITLE
Misformed LLVM_HOST_PATH environmental variable

### ISSUE THREAD

**Issue by jeff47** [Fail-Safe/openwrt-pesa1234-build#2]
OK, got another one for you:

At least on my system, and possibly others, line 74 in the Dockerfile to create the LLVM_HOST_PATH environmental variable isn't working properly.

```
user@5e7687140479:~/openwrt$ echo $LLVM_HOST_PATH
/usr/lib/$(ls /usr/lib/ | grep llvm | sort -r | head -1 | cut -d' ' -f11)
```

This means the CONFIG_BPF_TOOLCHAIN_HOST_PATH entry in .config is wrong, and I think it leads to the errors in compiling the bridger and qosify modules that I noticed.  Indeed, if I manually set LLVM_HOST_PATH to /usr/lib/llvm-18, the compile error goes away.  

Unless I'm mistaken, I don't think you can pipe a command into an ENV in a dockerfile like that.  I saw a few similar issues when searching the internet.

**Comment by Fail-Safe** [comment]
Thanks for finding and reporting this issue. I pushed a new commit that has resolved the issue in my testing. To apply this fix, you'll need to pull this commit and re-build the container image (by running script `#2`).

Fix:
https://github.com/Fail-Safe/openwrt-pesa1234-build/commit/42f5ae8a45fd9e283d135347e6c03be44017a1ac

**Comment by jeff47** [comment]
Looks good!
